Create README.md
Terasology/FunnyBlocks pull request #13
Opened 2018-01-07 23:46 UTC by NicholasBatesNZ

2018-01-08 00:53 UTC, vampcat requested changes
My biggest gripe is, this readme is meant for players as much as - if not more than - it is meant for developers. If I'm a person new to Terasology who just downloaded the game off the internet, saw this module called "FunnnyBlocks" and downloaded it, this readme does not really help me get started.

"Breaking Block"
But I don't see a breaking block in my inventory! Do I look around for a block, do I perform some ritual to please the block gods or do I simply type a command in the console? I don't know, and this readme does not explain that.

2018-01-08 06:27 UTC, NicholasBatesNZ commented
@vampcat I have added a "Playing" section that I think addresses this issue

2018-01-08 08:57 UTC, mjuvekar7 commented on README.md
> +2. Press the \` key and enter the command `give BlockName` where "BlockName" is the name of the desired block as taken from the list above. This block will appear in your inventory.
change \` to `~` (even though ~ is the secondary character on the key, the key is commonly known as the tilde key)

2018-01-08 08:57 UTC, mjuvekar7 commented
The rest looks good to me :)

2018-05-26 22:40 UTC, merged

2018-05-26 22:41 UTC, Cervator commented
Belated thanks for this :-)

The image hosting site changed, but I was able to figure out where the image went. But since they seemingly disallow hot linking I dumped the image file into this module's wiki repo instead, that way it doesn't bloat this repo yet is more reliably available. Both the readme and the wiki shows that image now 👍