Bouncy Block system
Terasology/FunnyBlocks pull request #5
Opened 2016-12-02 07:36 UTC by Setako

Added Bouncy Block system

2016-12-03 05:29 UTC, Cervator requested changes
Works great! Fun change, thank you very much :-)

Going to approve the task in the GCI system (sorry for taking a little while to get to it!) but leave the PR here open for some optimization cleanup. Could you also please delete the two `.class` files? They shouldn't be committed to source control :-)

2016-12-03 05:29 UTC, Cervator commented on .gitignore
> +build/
Tiny suggestion: add a newline at the bottom of all text files (some best practice that GitHub encourages with these little red marks)

2016-12-03 05:29 UTC, Cervator commented on assets/blocks/BouncyBlock.block
> +      "top": "funnyBlocks:BouncyBlock",
You can actually take out `top` and `bottom` - since the block name matches the texture that'll be the default anyway :-)

2016-12-03 05:29 UTC, Cervator commented on assets/blocks/BouncyBlock.block
> +      "sides": "funnyBlocks:BouncyBlock_side",
Suggestion: Rename `BouncyBlock_side` to `BouncyBlockSide` for consistency (both the file and the entry here)

2016-12-03 05:29 UTC, Cervator commented on assets/prefabs/BouncyBlock.prefab
> +	"name": "BouncyBlock",
Tab characters are eeeeevil :D Please use spaces. Long story, doesn't really matter ;-)

2016-12-03 05:29 UTC, Cervator commented on src/main/java/org/terasology/funnyblocks/component/BouncyBlockComponent.java
> +public class BouncyBlockComponent implements Component {
Maybe a short javadoc comment on the class here. Something like `/** Responsible for making blocks bouncy, trampoline style! */`

2016-12-03 05:29 UTC, Cervator commented on src/main/java/org/terasology/funnyblocks/system/BouncySystem.java
> +public class BouncySystem extends BaseComponentSystem implements UpdateSubscriberSystem
Looks like you're not using the `update()` method so you can actually take off the ` implements UpdateSubscriberSystem ` and remove the method

2016-12-03 05:29 UTC, Cervator commented on src/main/java/org/terasology/funnyblocks/system/BouncySystem.java
> +	private static final Logger logger = LoggerFactory.getLogger(BouncySystem.class);
This variable should be the top class variable (`private static` comes before plain `private`). In general https://github.com/MovingBlocks/Terasology/wiki/Checkstyle will help you spot code style issues like that :-)

2016-12-03 05:29 UTC, Cervator commented on src/main/java/org/terasology/funnyblocks/system/BouncySystem.java
> +	@In
Tab character here and in the rest of the class. Please replace with spaces :-)

2016-12-03 05:29 UTC, Cervator commented on src/main/java/org/terasology/funnyblocks/system/BouncySystem.java
> +			if(blockPos!=null && playerPosition!=null)
Another tiny Checkstyle fix: empty space on either side of `!=`

2016-12-03 05:56 UTC, Setako commented
@Cervator Fixed all problem! : )

2016-12-04 07:36 UTC, Cervator commented
Hey @Setako did the GCI task linked with this get moved back to review or even approved by now? It is hard to keep track in there :D I wonder if we should start attaching GCI task links to PRs here, would help!

2016-12-04 07:45 UTC, Setako commented
The gci task  was already approved, thanks :D

2016-12-05 06:26 UTC, Cervator commented
Oh! Okay good :-)

I can merge this whenever then, still works. Is the deletion of the speed boost files intentional though or something weird that snuck in?

2016-12-05 10:28 UTC, Setako commented
@Cervator The speed boost files I was deleted are .class compiled file.
You said:
> Could you also please delete the two .class files?

So I was added .class in .gitignore, then they was removed.
Should I keep them?

2016-12-06 18:45 UTC, Cervator commented
Thanks - just me getting myself confused there with so much stuff going on :-)

Checked it out again along with #7 which is subtly different in a nice way. Lots of funny blocks now!

2016-12-06 18:47 UTC, merged